### ISSUE TITLE
Non english characters problem

### ISSUE THREAD

**Issue by Zorrototo** [Seimax/AMC#1]
When you set non english characters like  é è ê à ç in the messages, it fails to properly display in game.
If I send the same message with non english characters from webadmin manually, it works, but when it is sent from the amc program those characters are replaced with weird things.

I tried to set the amc.ini encoding to ANSI or UTF-8 but it is the same.

Nice useful program by the way. 

edit: I actually will have more tests because it works from webadmin, but when I refresh the page it shows the chat history with wrong characters..

**Comment by Seimax** [comment]
Thanks for report... currently i have no idea whats going wrong and no time for debugging(have vacation in middle oct, think u have to wait until then). I checked allready all used libs for utf8 compatibility, but it seems like thats everywhere set to default. 

On which OS do u run AMC?

**Comment by Zorrototo** [comment]
I use Linux (Ubuntu 14.04) but AMC runs under WINE Staging 1.9.8 (I couldn't have the native Perl version to work, too much trouble with dependencies, I install the missing ones but it couldn't find them so in the end as my KF 2 server runs under WINE, I launched the windows version under WINE and it worked instantly)

But I need (still did not find time to test sorry :D) to test more  as the issue is maybe simply related to webadmin itself.

**Comment by Zorrototo** [comment]
Confirmed, sorry for false report, it is webadmin issue not your program (OK your program may have this kind of problem but we can't know until the webadmin itself does not produce this bug :D)

So for now, no issue, my bad.
